ARG TERRAFORM_IMAGE_TAG=1.8.2
ARG TERRAFORM_IMAGE=hashicorp/terraform:$TERRAFORM_IMAGE_TAG

ARG HARNESS_IMAGE_VERSION=latest
ARG HARNESS_IMAGE_TAG=${HARNESS_IMAGE_VERSION}-terraform$TERRAFORM_IMAGE_TAG
ARG HARNESS_IMAGE_REPO=harness-base
ARG HARNESS_IMAGE=$HARNESS_IMAGE_REPO:$HARNESS_IMAGE_TAG

FROM $TERRAFORM_IMAGE as terraform
FROM $HARNESS_IMAGE as final

COPY --from=terraform /bin/terraform /bin/terraform
