{{- if .Values.agentk.config.caCert }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "deployment-operator.fullname" . }}
  labels:
    {{- include "deployment-operator.labels" . | nindent 4 }}
data:
  ca.crt: {{ .Values.agentk.config.caCert | quote }}
{{- end }}


{{- range $cert := .Values.certs }}
{{- if and $cert.create $cert.name $cert.certData $cert.file }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "deployment-operator.fullname" $ }}-{{ $cert.name }}
  labels:
    {{- include "deployment-operator.labels" $ | nindent 4 }}
data:
  {{ $cert.file }}: {{ $cert.certData | quote }}
{{- else if $cert.create }}
{{- fail (printf "Certificate %s is missing required fields (name, certData or file)" $cert.name | default "unknown") }}
{{- end }}
{{- end }}