{{- if .Values.agentk.config.caCert }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "deployment-operator.fullname" . }}
  labels:
    {{- include "deployment-operator.labels" . | nindent 4 }}
data:
  ca.crt: {{ .Values.agentk.config.caCert | quote }}
{{- end }}


{{- range $cert := .Values.certs }}
{{- if $cert.create }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "deployment-operator.fullname" . }}-{{ $cert.name }}
  labels:
    {{- include "deployment-operator.labels" . | nindent 4 }}
data:
  {{ $cert.name }}.crt: {{ $cert.certData | quote }}
{{- end }}
{{- end }}