{{- if and ((.Values.agentk.config.observability).tls).enabled
           (((.Values.agentk.config.observability).tls).secret).create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "agentk.observabilitySecretName" . }}
  labels:
    {{- include "deployment-operator.labels" . | nindent 4 }}
data:
  tls.key: {{ .Values.agentk.config.observability.tls.key | b64enc }}
  tls.crt: {{ .Values.agentk.config.observability.tls.cert | b64enc }}
type: kubernetes.io/tls
{{- end }}
