apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: deployment-operator-binding
  labels:
{{ include "deployment-operator.labels" . | indent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "deployment-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ .Values.rbac.clusterRole }}
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: plrl-console-reader
  labels:
{{ include "deployment-operator.labels" . | indent 4 }}
rules:
- apiGroups: ["", "*"]
  resources: ["*"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["delete"]
- apiGroups: ["deployments.plural.sh"]
  resources: ["customhealths"]
  verbs: ["create","delete","get", "list", "patch", "update", "watch"]
- apiGroups: ["deployments.plural.sh"]
  resources: ["customhealths/finalizers"]
  verbs: ["update"]
- apiGroups: ["deployments.plural.sh"]
  resources: ["customhealths/status"]
  verbs: ["get", "patch", "update", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: console-read-binding
  labels:
{{ include "deployment-operator.labels" . | indent 4 }}
subjects:
- kind: User
  name: console@plural.sh
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: plrl-console-reader
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: plrl-agent-gate-operator
  labels:
{{ include "deployment-operator.labels" . | indent 4 }}
rules:
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
- apiGroups: ["pipelines.plural.sh"]
  resources: ["pipelinegates"]
  verbs: ["create","delete","get", "list", "patch", "update", "watch"]
- apiGroups: ["pipelines.plural.sh"]
  resources: ["pipelinegates/finalizers"]
  verbs: ["update"]
- apiGroups: ["pipelines.plural.sh"]
  resources: ["pipelinegates/status"]
  verbs: ["get", "patch", "update", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: plrl-agent-gate-operator-binding
  labels:
{{ include "deployment-operator.labels" . | indent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "deployment-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: plrl-agent-gate-operator
  apiGroup: rbac.authorization.k8s.io
