apiVersion: v1
kind: Secret
metadata:
  name: deployment-operator-env
  labels:
{{ include "deployment-operator.labels" . | indent 4 }}
type: Opaque
stringData:
  DEPLOY_TOKEN: {{ .Values.secrets.deployToken }}
  {{- if .Values.ferrotunnel.enabled }}
  FERROTUNNEL_TOKEN: {{ .Values.ferrotunnel.token | quote }}
  FERROTUNNEL_CA: {{ .Values.ferrotunnel.ca | b64dec | quote }}
  FERROTUNNEL_CERT: {{ .Values.ferrotunnel.cert | b64dec | quote }}
  FERROTUNNEL_KEY: {{ .Values.ferrotunnel.key | b64dec | quote }}
  {{- end }} 