{{- if and .Values.tunnelController.enabled .Values.tunnelController.server .Values.tunnelController.token }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.tunnelController.tokenSecret.name }}
  labels:
    app.kubernetes.io/component: tunnel-controller
    {{- include "deployment-operator.labels" . | nindent 4 }}
type: Opaque
data:
  token: {{ .Values.tunnelController.token | b64enc }}
  ca.crt: {{ .Values.tunnelController.ca }}
  tls.crt: {{ .Values.tunnelController.cert }}
  tls.key: {{ .Values.tunnelController.key }}
{{- end }}
