apiVersion: v1
kind: Secret
metadata:
  name: deployment-operator-env
  labels:
{{ include "deployment-operator.labels" . | indent 4 }}
type: Opaque
stringData:
  DEPLOY_TOKEN: {{ .Values.secrets.deployToken }} 