# Node image version is controlled in the agent-harness images themselves.
ARG VERSION

ARG AGENT_HARNESS_IMAGE_TAG
ARG AGENT_HARNESS_IMAGE_REPO
ARG AGENT_HARNESS_IMAGE=$AGENT_HARNESS_IMAGE_REPO:$AGENT_HARNESS_IMAGE_TAG

FROM $AGENT_HARNESS_IMAGE AS final
