ARG PYTHON_IMAGE_TAG=3.14-slim
ARG PYTHON_IMAGE=python:${PYTHON_IMAGE_TAG}

ARG AGENT_HARNESS_IMAGE_TAG
ARG AGENT_HARNESS_IMAGE_REPO
ARG AGENT_HARNESS_IMAGE=$AGENT_HARNESS_IMAGE_REPO:$AGENT_HARNESS_IMAGE_TAG

FROM $PYTHON_IMAGE AS python

FROM $AGENT_HARNESS_IMAGE AS final

COPY --from=python /usr/local /usr/local
COPY --from=python /usr/lib /usr/lib
