ARG AG=3.14-slim

ARG AGENT_HARNESS_IMAGE_TAG
ARG AGENT_HARNESS_IMAGE_REPO
ARG AGENT_HARNESS_IMAGE=$AGENT_HARNESS_IMAGE_REPO:$AGENT_HARNESS_IMAGE_TAG

FROM python:${TAG} AS python

FROM $AGENT_HARNESS_IMAGE AS final

COPY --from=python /usr/local /usr/local
COPY --from=python /usr/lib /usr/lib
