// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.24.3
// source: proto/deployment.proto

package deployment

import (
	"reflect"
	"sync"

	"google.golang.org/protobuf/reflect/protoreflect"
	"google.golang.org/protobuf/runtime/protoimpl"
	"google.golang.org/protobuf/types/descriptorpb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// S3SignatureVersion is the version of the signing algorithm for all s3 requests
type S3SignatureVersion int32

const (
	S3SignatureVersion_UnknownSignature S3SignatureVersion = 0
	// S3V2, Signature version v2
	S3SignatureVersion_S3V2 S3SignatureVersion = 1
	// S3V4, Signature version v4
	S3SignatureVersion_S3V4 S3SignatureVersion = 2
)

// Enum value maps for S3SignatureVersion.
var (
	S3SignatureVersion_name = map[int32]string{
		0: "UnknownSignature",
		1: "S3V2",
		2: "S3V4",
	}
	S3SignatureVersion_value = map[string]int32{
		"UnknownSignature": 0,
		"S3V2":             1,
		"S3V4":             2,
	}
)

func (x S3SignatureVersion) Enum() *S3SignatureVersion {
	p := new(S3SignatureVersion)
	*p = x
	return p
}

func (x S3SignatureVersion) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (S3SignatureVersion) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_deployment_proto_enumTypes[0].Descriptor()
}

func (S3SignatureVersion) Type() protoreflect.EnumType {
	return &file_proto_deployment_proto_enumTypes[0]
}

func (x S3SignatureVersion) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use S3SignatureVersion.Descriptor instead.
func (S3SignatureVersion) EnumDescriptor() ([]byte, []int) {
	return file_proto_deployment_proto_rawDescGZIP(), []int{0}
}

type AnonymousDeploymentAccessMode int32

const (
	AnonymousDeploymentAccessMode_UnknownDeploymentAccessMode AnonymousDeploymentAccessMode = 0
	// Default, disallow uncredentialed access to the backend storage.
	AnonymousDeploymentAccessMode_Private AnonymousDeploymentAccessMode = 1
	// Read only, uncredentialed users can call ListDeployment and GetObject.
	AnonymousDeploymentAccessMode_ReadOnly AnonymousDeploymentAccessMode = 2
	// Write only, uncredentialed users can only call PutObject.
	AnonymousDeploymentAccessMode_WriteOnly AnonymousDeploymentAccessMode = 3
	// Read/Write, uncredentialed users can read objects as well as PutObject.
	AnonymousDeploymentAccessMode_ReadWrite AnonymousDeploymentAccessMode = 4
)

// Enum value maps for AnonymousDeploymentAccessMode.
var (
	AnonymousDeploymentAccessMode_name = map[int32]string{
		0: "UnknownDeploymentAccessMode",
		1: "Private",
		2: "ReadOnly",
		3: "WriteOnly",
		4: "ReadWrite",
	}
	AnonymousDeploymentAccessMode_value = map[string]int32{
		"UnknownDeploymentAccessMode": 0,
		"Private":                     1,
		"ReadOnly":                    2,
		"WriteOnly":                   3,
		"ReadWrite":                   4,
	}
)

func (x AnonymousDeploymentAccessMode) Enum() *AnonymousDeploymentAccessMode {
	p := new(AnonymousDeploymentAccessMode)
	*p = x
	return p
}

func (x AnonymousDeploymentAccessMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AnonymousDeploymentAccessMode) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_deployment_proto_enumTypes[1].Descriptor()
}

func (AnonymousDeploymentAccessMode) Type() protoreflect.EnumType {
	return &file_proto_deployment_proto_enumTypes[1]
}

func (x AnonymousDeploymentAccessMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AnonymousDeploymentAccessMode.Descriptor instead.
func (AnonymousDeploymentAccessMode) EnumDescriptor() ([]byte, []int) {
	return file_proto_deployment_proto_rawDescGZIP(), []int{1}
}

type AuthenticationType int32

const (
	AuthenticationType_UnknownAuthenticationType AuthenticationType = 0
	// Default, KEY based authentication.
	AuthenticationType_Key AuthenticationType = 1
	// Storageaccount based authentication.
	AuthenticationType_IAM AuthenticationType = 2
)

// Enum value maps for AuthenticationType.
var (
	AuthenticationType_name = map[int32]string{
		0: "UnknownAuthenticationType",
		1: "Key",
		2: "IAM",
	}
	AuthenticationType_value = map[string]int32{
		"UnknownAuthenticationType": 0,
		"Key":                       1,
		"IAM":                       2,
	}
)

func (x AuthenticationType) Enum() *AuthenticationType {
	p := new(AuthenticationType)
	*p = x
	return p
}

func (x AuthenticationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AuthenticationType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_deployment_proto_enumTypes[2].Descriptor()
}

func (AuthenticationType) Type() protoreflect.EnumType {
	return &file_proto_deployment_proto_enumTypes[2]
}

func (x AuthenticationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AuthenticationType.Descriptor instead.
func (AuthenticationType) EnumDescriptor() ([]byte, []int) {
	return file_proto_deployment_proto_rawDescGZIP(), []int{2}
}

type DeploymentStatusEnum struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Type:
	//
	//	*DeploymentStatusEnum_Ready
	//	*DeploymentStatusEnum_Pending
	//	*DeploymentStatusEnum_Error
	Type isDeploymentStatusEnum_Type `protobuf_oneof:"type"`
}

func (x *DeploymentStatusEnum) Reset() {
	*x = DeploymentStatusEnum{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_deployment_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeploymentStatusEnum) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeploymentStatusEnum) ProtoMessage() {}

func (x *DeploymentStatusEnum) ProtoReflect() protoreflect.Message {
	mi := &file_proto_deployment_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeploymentStatusEnum.ProtoReflect.Descriptor instead.
func (*DeploymentStatusEnum) Descriptor() ([]byte, []int) {
	return file_proto_deployment_proto_rawDescGZIP(), []int{0}
}

func (m *DeploymentStatusEnum) GetType() isDeploymentStatusEnum_Type {
	if m != nil {
		return m.Type
	}
	return nil
}

func (x *DeploymentStatusEnum) GetReady() bool {
	if x, ok := x.GetType().(*DeploymentStatusEnum_Ready); ok {
		return x.Ready
	}
	return false
}

func (x *DeploymentStatusEnum) GetPending() bool {
	if x, ok := x.GetType().(*DeploymentStatusEnum_Pending); ok {
		return x.Pending
	}
	return false
}

func (x *DeploymentStatusEnum) GetError() bool {
	if x, ok := x.GetType().(*DeploymentStatusEnum_Error); ok {
		return x.Error
	}
	return false
}

type isDeploymentStatusEnum_Type interface {
	isDeploymentStatusEnum_Type()
}

type DeploymentStatusEnum_Ready struct {
	Ready bool `protobuf:"varint,1,opt,name=ready,proto3,oneof"`
}

type DeploymentStatusEnum_Pending struct {
	Pending bool `protobuf:"varint,2,opt,name=pending,proto3,oneof"`
}

type DeploymentStatusEnum_Error struct {
	Error bool `protobuf:"varint,3,opt,name=error,proto3,oneof"`
}

func (*DeploymentStatusEnum_Ready) isDeploymentStatusEnum_Type() {}

func (*DeploymentStatusEnum_Pending) isDeploymentStatusEnum_Type() {}

func (*DeploymentStatusEnum_Error) isDeploymentStatusEnum_Type() {}

type CredentialDetails struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// map of the details in the secrets for the protocol string
	Secrets map[string]string `protobuf:"bytes,1,rep,name=secrets,proto3" json:"secrets,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *CredentialDetails) Reset() {
	*x = CredentialDetails{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_deployment_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CredentialDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CredentialDetails) ProtoMessage() {}

func (x *CredentialDetails) ProtoReflect() protoreflect.Message {
	mi := &file_proto_deployment_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CredentialDetails.ProtoReflect.Descriptor instead.
func (*CredentialDetails) Descriptor() ([]byte, []int) {
	return file_proto_deployment_proto_rawDescGZIP(), []int{1}
}

func (x *CredentialDetails) GetSecrets() map[string]string {
	if x != nil {
		return x.Secrets
	}
	return nil
}

type DriverGetInfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DriverGetInfoRequest) Reset() {
	*x = DriverGetInfoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_deployment_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DriverGetInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriverGetInfoRequest) ProtoMessage() {}

func (x *DriverGetInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_deployment_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriverGetInfoRequest.ProtoReflect.Descriptor instead.
func (*DriverGetInfoRequest) Descriptor() ([]byte, []int) {
	return file_proto_deployment_proto_rawDescGZIP(), []int{2}
}

type DriverGetInfoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// This field is REQUIRED
	// The name MUST follow domain name notation format
	// (https://tools.ietf.org/html/rfc1035#section-2.3.1). It SHOULD
	// include the plugin's host company name and the plugin name,
	// to minimize the possibility of collisions. It MUST be 63
	// characters or less, beginning and ending with an alphanumeric
	// character ([a-z0-9A-Z]) with dashes (-), dots (.), and
	// alphanumerics between.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *DriverGetInfoResponse) Reset() {
	*x = DriverGetInfoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_deployment_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DriverGetInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriverGetInfoResponse) ProtoMessage() {}

func (x *DriverGetInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_deployment_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriverGetInfoResponse.ProtoReflect.Descriptor instead.
func (*DriverGetInfoResponse) Descriptor() ([]byte, []int) {
	return file_proto_deployment_proto_rawDescGZIP(), []int{3}
}

func (x *DriverGetInfoResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DriverCreateDeploymentRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// This field is REQUIRED
	// name specifies the name of the deployment that should be created.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// This field is OPTIONAL
	// The caller should treat the values in parameters as opaque.
	// The receiver is responsible for parsing and validating the values.
	Parameters map[string]string `protobuf:"bytes,2,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *DriverCreateDeploymentRequest) Reset() {
	*x = DriverCreateDeploymentRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_deployment_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DriverCreateDeploymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriverCreateDeploymentRequest) ProtoMessage() {}

func (x *DriverCreateDeploymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_deployment_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriverCreateDeploymentRequest.ProtoReflect.Descriptor instead.
func (*DriverCreateDeploymentRequest) Descriptor() ([]byte, []int) {
	return file_proto_deployment_proto_rawDescGZIP(), []int{4}
}

func (x *DriverCreateDeploymentRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DriverCreateDeploymentRequest) GetParameters() map[string]string {
	if x != nil {
		return x.Parameters
	}
	return nil
}

type DriverCreateDeploymentResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// deployment_id returned here is expected to be the globally unique
	// identifier for the deployment in the object storage provider.
	DeploymentId string `protobuf:"bytes,1,opt,name=deployment_id,json=deploymentId,proto3" json:"deployment_id,omitempty"`
}

func (x *DriverCreateDeploymentResponse) Reset() {
	*x = DriverCreateDeploymentResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_deployment_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DriverCreateDeploymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriverCreateDeploymentResponse) ProtoMessage() {}

func (x *DriverCreateDeploymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_deployment_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriverCreateDeploymentResponse.ProtoReflect.Descriptor instead.
func (*DriverCreateDeploymentResponse) Descriptor() ([]byte, []int) {
	return file_proto_deployment_proto_rawDescGZIP(), []int{5}
}

func (x *DriverCreateDeploymentResponse) GetDeploymentId() string {
	if x != nil {
		return x.DeploymentId
	}
	return ""
}

type DriverDeleteDeploymentRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// This field is REQUIRED
	// deployment_id is a globally unique identifier for the deployment
	// in the object storage provider
	DeploymentId string `protobuf:"bytes,1,opt,name=deployment_id,json=deploymentId,proto3" json:"deployment_id,omitempty"`
}

func (x *DriverDeleteDeploymentRequest) Reset() {
	*x = DriverDeleteDeploymentRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_deployment_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DriverDeleteDeploymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriverDeleteDeploymentRequest) ProtoMessage() {}

func (x *DriverDeleteDeploymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_deployment_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriverDeleteDeploymentRequest.ProtoReflect.Descriptor instead.
func (*DriverDeleteDeploymentRequest) Descriptor() ([]byte, []int) {
	return file_proto_deployment_proto_rawDescGZIP(), []int{6}
}

func (x *DriverDeleteDeploymentRequest) GetDeploymentId() string {
	if x != nil {
		return x.DeploymentId
	}
	return ""
}

type DriverGetDeploymentStatusRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// This field is REQUIRED
	// deployment_id is a globally unique identifier for the deployment
	// in the object storage provider
	DeploymentId string `protobuf:"bytes,1,opt,name=deployment_id,json=deploymentId,proto3" json:"deployment_id,omitempty"`
}

func (x *DriverGetDeploymentStatusRequest) Reset() {
	*x = DriverGetDeploymentStatusRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_deployment_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DriverGetDeploymentStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriverGetDeploymentStatusRequest) ProtoMessage() {}

func (x *DriverGetDeploymentStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_deployment_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriverGetDeploymentStatusRequest.ProtoReflect.Descriptor instead.
func (*DriverGetDeploymentStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_deployment_proto_rawDescGZIP(), []int{7}
}

func (x *DriverGetDeploymentStatusRequest) GetDeploymentId() string {
	if x != nil {
		return x.DeploymentId
	}
	return ""
}

type DriverGetDeploymentStatusResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// deployment_id returned here is expected to be the globally unique
	// identifier for the deployment in the object storage provider.
	DeploymentId     string                `protobuf:"bytes,1,opt,name=deployment_id,json=deploymentId,proto3" json:"deployment_id,omitempty"`
	DeploymentStatus *DeploymentStatusEnum `protobuf:"bytes,2,opt,name=deployment_status,json=deploymentStatus,proto3" json:"deployment_status,omitempty"`
	Message          string                `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *DriverGetDeploymentStatusResponse) Reset() {
	*x = DriverGetDeploymentStatusResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_deployment_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DriverGetDeploymentStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriverGetDeploymentStatusResponse) ProtoMessage() {}

func (x *DriverGetDeploymentStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_deployment_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriverGetDeploymentStatusResponse.ProtoReflect.Descriptor instead.
func (*DriverGetDeploymentStatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_deployment_proto_rawDescGZIP(), []int{8}
}

func (x *DriverGetDeploymentStatusResponse) GetDeploymentId() string {
	if x != nil {
		return x.DeploymentId
	}
	return ""
}

func (x *DriverGetDeploymentStatusResponse) GetDeploymentStatus() *DeploymentStatusEnum {
	if x != nil {
		return x.DeploymentStatus
	}
	return nil
}

func (x *DriverGetDeploymentStatusResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DriverDeleteDeploymentResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DriverDeleteDeploymentResponse) Reset() {
	*x = DriverDeleteDeploymentResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_deployment_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DriverDeleteDeploymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriverDeleteDeploymentResponse) ProtoMessage() {}

func (x *DriverDeleteDeploymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_deployment_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriverDeleteDeploymentResponse.ProtoReflect.Descriptor instead.
func (*DriverDeleteDeploymentResponse) Descriptor() ([]byte, []int) {
	return file_proto_deployment_proto_rawDescGZIP(), []int{9}
}

var file_proto_deployment_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.EnumOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         1116,
		Name:          "deployment.v1alpha1.alpha_enum",
		Tag:           "varint,1116,opt,name=alpha_enum",
		Filename:      "proto/deployment.proto",
	},
	{
		ExtendedType:  (*descriptorpb.EnumValueOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         1116,
		Name:          "deployment.v1alpha1.alpha_enum_value",
		Tag:           "varint,1116,opt,name=alpha_enum_value",
		Filename:      "proto/deployment.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         1115,
		Name:          "deployment.v1alpha1.deployment_secret",
		Tag:           "varint,1115,opt,name=deployment_secret",
		Filename:      "proto/deployment.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         1116,
		Name:          "deployment.v1alpha1.alpha_field",
		Tag:           "varint,1116,opt,name=alpha_field",
		Filename:      "proto/deployment.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         1116,
		Name:          "deployment.v1alpha1.alpha_message",
		Tag:           "varint,1116,opt,name=alpha_message",
		Filename:      "proto/deployment.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         1116,
		Name:          "deployment.v1alpha1.alpha_method",
		Tag:           "varint,1116,opt,name=alpha_method",
		Filename:      "proto/deployment.proto",
	},
	{
		ExtendedType:  (*descriptorpb.ServiceOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         1116,
		Name:          "deployment.v1alpha1.alpha_service",
		Tag:           "varint,1116,opt,name=alpha_service",
		Filename:      "proto/deployment.proto",
	},
}

// Extension fields to descriptorpb.EnumOptions.
var (
	// Indicates that this enum is OPTIONAL and part of an experimental
	// API that may be deprecated and eventually removed between minor
	// releases.
	//
	// optional bool alpha_enum = 1116;
	E_AlphaEnum = &file_proto_deployment_proto_extTypes[0]
)

// Extension fields to descriptorpb.EnumValueOptions.
var (
	// Indicates that this enum value is OPTIONAL and part of an
	// experimental API that may be deprecated and eventually removed
	// between minor releases.
	//
	// optional bool alpha_enum_value = 1116;
	E_AlphaEnumValue = &file_proto_deployment_proto_extTypes[1]
)

// Extension fields to descriptorpb.FieldOptions.
var (
	// Indicates that a field MAY contain information that is sensitive
	// and MUST be treated as such (e.g. not logged).
	//
	// optional bool deployment_secret = 1115;
	E_DeploymentSecret = &file_proto_deployment_proto_extTypes[2]
	// Indicates that this field is OPTIONAL and part of an experimental
	// API that may be deprecated and eventually removed between minor
	// releases.
	//
	// optional bool alpha_field = 1116;
	E_AlphaField = &file_proto_deployment_proto_extTypes[3]
)

// Extension fields to descriptorpb.MessageOptions.
var (
	// Indicates that this message is OPTIONAL and part of an experimental
	// API that may be deprecated and eventually removed between minor
	// releases.
	//
	// optional bool alpha_message = 1116;
	E_AlphaMessage = &file_proto_deployment_proto_extTypes[4]
)

// Extension fields to descriptorpb.MethodOptions.
var (
	// Indicates that this method is OPTIONAL and part of an experimental
	// API that may be deprecated and eventually removed between minor
	// releases.
	//
	// optional bool alpha_method = 1116;
	E_AlphaMethod = &file_proto_deployment_proto_extTypes[5]
)

// Extension fields to descriptorpb.ServiceOptions.
var (
	// Indicates that this service is OPTIONAL and part of an experimental
	// API that may be deprecated and eventually removed between minor
	// releases.
	//
	// optional bool alpha_service = 1116;
	E_AlphaService = &file_proto_deployment_proto_extTypes[6]
)

var File_proto_deployment_proto protoreflect.FileDescriptor

var file_proto_deployment_proto_rawDesc = []byte{
	0x0a, 0x16, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x64, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x6d, 0x65,
	0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x13, 0x64, 0x65, 0x70, 0x6c, 0x6f, 0x79,
	0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x1a, 0x20, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x64,
	0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x6a, 0x0a, 0x14, 0x44, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x45, 0x6e, 0x75, 0x6d, 0x12, 0x16, 0x0a, 0x05, 0x72, 0x65, 0x61, 0x64, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x48, 0x00, 0x52, 0x05, 0x72, 0x65, 0x61, 0x64, 0x79, 0x12,
	0x1a, 0x0a, 0x07, 0x70, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08,
	0x48, 0x00, 0x52, 0x07, 0x70, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x12, 0x16, 0x0a, 0x05, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x48, 0x00, 0x52, 0x05, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x42, 0x06, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x9e, 0x01, 0x0a, 0x11,
	0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c,
	0x73, 0x12, 0x4d, 0x0a, 0x07, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x33, 0x2e, 0x64, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x2e,
	0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74,
	0x69, 0x61, 0x6c, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x2e, 0x53, 0x65, 0x63, 0x72, 0x65,
	0x74, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x07, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x73,
	0x1a, 0x3a, 0x0a, 0x0c, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79,
	0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b,
	0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x16, 0x0a, 0x14,
	0x44, 0x72, 0x69, 0x76, 0x65, 0x72, 0x47, 0x65, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x22, 0x2b, 0x0a, 0x15, 0x44, 0x72, 0x69, 0x76, 0x65, 0x72, 0x47, 0x65,
	0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x22, 0xd6, 0x01, 0x0a, 0x1d, 0x44, 0x72, 0x69, 0x76, 0x65, 0x72, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x44, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x62, 0x0a, 0x0a, 0x70, 0x61, 0x72, 0x61, 0x6d,
	0x65, 0x74, 0x65, 0x72, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x42, 0x2e, 0x64, 0x65,
	0x70, 0x6c, 0x6f, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61,
	0x31, 0x2e, 0x44, 0x72, 0x69, 0x76, 0x65, 0x72, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x44, 0x65,
	0x70, 0x6c, 0x6f, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e,
	0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52,
	0x0a, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x73, 0x1a, 0x3d, 0x0a, 0x0f, 0x50,
	0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10,
	0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79,
	0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x45, 0x0a, 0x1e, 0x44, 0x72,
	0x69, 0x76, 0x65, 0x72, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x44, 0x65, 0x70, 0x6c, 0x6f, 0x79,
	0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x23, 0x0a, 0x0d,
	0x64, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0c, 0x64, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x49,
	0x64, 0x22, 0x44, 0x0a, 0x1d, 0x44, 0x72, 0x69, 0x76, 0x65, 0x72, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x44, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x23, 0x0a, 0x0d, 0x64, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x6d, 0x65, 0x6e, 0x74,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x64, 0x65, 0x70, 0x6c, 0x6f,
	0x79, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x22, 0x47, 0x0a, 0x20, 0x44, 0x72, 0x69, 0x76, 0x65,
	0x72, 0x47, 0x65, 0x74, 0x44, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x23, 0x0a, 0x0d, 0x64,
	0x65, 0x70, 0x6c, 0x6f, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0c, 0x64, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64,
	0x22, 0xba, 0x01, 0x0a, 0x21, 0x44, 0x72, 0x69, 0x76, 0x65, 0x72, 0x47, 0x65, 0x74, 0x44, 0x65,
	0x70, 0x6c, 0x6f, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x64, 0x65, 0x70, 0x6c, 0x6f, 0x79,
	0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x64,
	0x65, 0x70, 0x6c, 0x6f, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x56, 0x0a, 0x11, 0x64,
	0x65, 0x70, 0x6c, 0x6f, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x29, 0x2e, 0x64, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x6d,
	0x65, 0x6e, 0x74, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x44, 0x65, 0x70,
	0x6c, 0x6f, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x45, 0x6e, 0x75,
	0x6d, 0x52, 0x10, 0x64, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x20, 0x0a,
	0x1e, 0x44, 0x72, 0x69, 0x76, 0x65, 0x72, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x44, 0x65, 0x70,
	0x6c, 0x6f, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2a,
	0x3e, 0x0a, 0x12, 0x53, 0x33, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x56, 0x65,
	0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x10, 0x55, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e,
	0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x53,
	0x33, 0x56, 0x32, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x53, 0x33, 0x56, 0x34, 0x10, 0x02, 0x2a,
	0x79, 0x0a, 0x1d, 0x41, 0x6e, 0x6f, 0x6e, 0x79, 0x6d, 0x6f, 0x75, 0x73, 0x44, 0x65, 0x70, 0x6c,
	0x6f, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x4d, 0x6f, 0x64, 0x65,
	0x12, 0x1f, 0x0a, 0x1b, 0x55, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x44, 0x65, 0x70, 0x6c, 0x6f,
	0x79, 0x6d, 0x65, 0x6e, 0x74, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x4d, 0x6f, 0x64, 0x65, 0x10,
	0x00, 0x12, 0x0b, 0x0a, 0x07, 0x50, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x10, 0x01, 0x12, 0x0c,
	0x0a, 0x08, 0x52, 0x65, 0x61, 0x64, 0x4f, 0x6e, 0x6c, 0x79, 0x10, 0x02, 0x12, 0x0d, 0x0a, 0x09,
	0x57, 0x72, 0x69, 0x74, 0x65, 0x4f, 0x6e, 0x6c, 0x79, 0x10, 0x03, 0x12, 0x0d, 0x0a, 0x09, 0x52,
	0x65, 0x61, 0x64, 0x57, 0x72, 0x69, 0x74, 0x65, 0x10, 0x04, 0x2a, 0x45, 0x0a, 0x12, 0x41, 0x75,
	0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x1d, 0x0a, 0x19, 0x55, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x41, 0x75, 0x74, 0x68, 0x65,
	0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x10, 0x00, 0x12,
	0x07, 0x0a, 0x03, 0x4b, 0x65, 0x79, 0x10, 0x01, 0x12, 0x07, 0x0a, 0x03, 0x49, 0x41, 0x4d, 0x10,
	0x02, 0x32, 0x74, 0x0a, 0x08, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x68, 0x0a,
	0x0d, 0x44, 0x72, 0x69, 0x76, 0x65, 0x72, 0x47, 0x65, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x29,
	0x2e, 0x64, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x76, 0x31, 0x61, 0x6c,
	0x70, 0x68, 0x61, 0x31, 0x2e, 0x44, 0x72, 0x69, 0x76, 0x65, 0x72, 0x47, 0x65, 0x74, 0x49, 0x6e,
	0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2a, 0x2e, 0x64, 0x65, 0x70, 0x6c,
	0x6f, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e,
	0x44, 0x72, 0x69, 0x76, 0x65, 0x72, 0x47, 0x65, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x32, 0xa8, 0x03, 0x0a, 0x0b, 0x50, 0x72, 0x6f, 0x76,
	0x69, 0x73, 0x69, 0x6f, 0x6e, 0x65, 0x72, 0x12, 0x83, 0x01, 0x0a, 0x16, 0x44, 0x72, 0x69, 0x76,
	0x65, 0x72, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x44, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x6d, 0x65,
	0x6e, 0x74, 0x12, 0x32, 0x2e, 0x64, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x2e,
	0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x44, 0x72, 0x69, 0x76, 0x65, 0x72, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x44, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x33, 0x2e, 0x64, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x6d,
	0x65, 0x6e, 0x74, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x44, 0x72, 0x69,
	0x76, 0x65, 0x72, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x44, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x6d,
	0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x83, 0x01,
	0x0a, 0x16, 0x44, 0x72, 0x69, 0x76, 0x65, 0x72, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x44, 0x65,
	0x70, 0x6c, 0x6f, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x32, 0x2e, 0x64, 0x65, 0x70, 0x6c, 0x6f,
	0x79, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x44,
	0x72, 0x69, 0x76, 0x65, 0x72, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x44, 0x65, 0x70, 0x6c, 0x6f,
	0x79, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x33, 0x2e, 0x64,
	0x65, 0x70, 0x6c, 0x6f, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68,
	0x61, 0x31, 0x2e, 0x44, 0x72, 0x69, 0x76, 0x65, 0x72, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x44,
	0x65, 0x70, 0x6c, 0x6f, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x12, 0x8c, 0x01, 0x0a, 0x19, 0x44, 0x72, 0x69, 0x76, 0x65, 0x72, 0x47, 0x65,
	0x74, 0x44, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x12, 0x35, 0x2e, 0x64, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x76,
	0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x44, 0x72, 0x69, 0x76, 0x65, 0x72, 0x47, 0x65,
	0x74, 0x44, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x36, 0x2e, 0x64, 0x65, 0x70, 0x6c, 0x6f,
	0x79, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x44,
	0x72, 0x69, 0x76, 0x65, 0x72, 0x47, 0x65, 0x74, 0x44, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x6d, 0x65,
	0x6e, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x3a, 0x3c, 0x0a, 0x0a, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x5f, 0x65, 0x6e, 0x75, 0x6d,
	0x12, 0x1c, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x45, 0x6e, 0x75, 0x6d, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0xdc,
	0x08, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x45, 0x6e, 0x75, 0x6d,
	0x3a, 0x4c, 0x0a, 0x10, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x5f, 0x65, 0x6e, 0x75, 0x6d, 0x5f, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x12, 0x21, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6e, 0x75, 0x6d, 0x56, 0x61, 0x6c, 0x75, 0x65,
	0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0xdc, 0x08, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0e,
	0x61, 0x6c, 0x70, 0x68, 0x61, 0x45, 0x6e, 0x75, 0x6d, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x4b,
	0x0a, 0x11, 0x64, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x73, 0x65, 0x63,
	0x72, 0x65, 0x74, 0x12, 0x1d, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x4f, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x18, 0xdb, 0x08, 0x20, 0x01, 0x28, 0x08, 0x52, 0x10, 0x64, 0x65, 0x70, 0x6c, 0x6f,
	0x79, 0x6d, 0x65, 0x6e, 0x74, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x3a, 0x3f, 0x0a, 0x0b, 0x61,
	0x6c, 0x70, 0x68, 0x61, 0x5f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x1d, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x46, 0x69, 0x65,
	0x6c, 0x64, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0xdc, 0x08, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x0a, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x3a, 0x45, 0x0a, 0x0d,
	0x61, 0x6c, 0x70, 0x68, 0x61, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1f, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0xdc,
	0x08, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0c, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x3a, 0x42, 0x0a, 0x0c, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x5f, 0x6d, 0x65, 0x74,
	0x68, 0x6f, 0x64, 0x12, 0x1e, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x4f, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x18, 0xdc, 0x08, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x61, 0x6c, 0x70, 0x68,
	0x61, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x3a, 0x45, 0x0a, 0x0d, 0x61, 0x6c, 0x70, 0x68, 0x61,
	0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x1f, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0xdc, 0x08, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x0c, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x42, 0x35,
	0x5a, 0x33, 0x70, 0x6c, 0x75, 0x72, 0x61, 0x6c, 0x73, 0x68, 0x2f, 0x64, 0x65, 0x70, 0x6c, 0x6f,
	0x79, 0x6d, 0x65, 0x6e, 0x74, 0x2d, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x2f, 0x70,
	0x72, 0x6f, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x65, 0x72, 0x3b, 0x64, 0x65, 0x70, 0x6c, 0x6f,
	0x79, 0x6d, 0x65, 0x6e, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_deployment_proto_rawDescOnce sync.Once
	file_proto_deployment_proto_rawDescData = file_proto_deployment_proto_rawDesc
)

func file_proto_deployment_proto_rawDescGZIP() []byte {
	file_proto_deployment_proto_rawDescOnce.Do(func() {
		file_proto_deployment_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_deployment_proto_rawDescData)
	})
	return file_proto_deployment_proto_rawDescData
}

var file_proto_deployment_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_proto_deployment_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_proto_deployment_proto_goTypes = []interface{}{
	(S3SignatureVersion)(0),                   // 0: deployment.v1alpha1.S3SignatureVersion
	(AnonymousDeploymentAccessMode)(0),        // 1: deployment.v1alpha1.AnonymousDeploymentAccessMode
	(AuthenticationType)(0),                   // 2: deployment.v1alpha1.AuthenticationType
	(*DeploymentStatusEnum)(nil),              // 3: deployment.v1alpha1.DeploymentStatusEnum
	(*CredentialDetails)(nil),                 // 4: deployment.v1alpha1.CredentialDetails
	(*DriverGetInfoRequest)(nil),              // 5: deployment.v1alpha1.DriverGetInfoRequest
	(*DriverGetInfoResponse)(nil),             // 6: deployment.v1alpha1.DriverGetInfoResponse
	(*DriverCreateDeploymentRequest)(nil),     // 7: deployment.v1alpha1.DriverCreateDeploymentRequest
	(*DriverCreateDeploymentResponse)(nil),    // 8: deployment.v1alpha1.DriverCreateDeploymentResponse
	(*DriverDeleteDeploymentRequest)(nil),     // 9: deployment.v1alpha1.DriverDeleteDeploymentRequest
	(*DriverGetDeploymentStatusRequest)(nil),  // 10: deployment.v1alpha1.DriverGetDeploymentStatusRequest
	(*DriverGetDeploymentStatusResponse)(nil), // 11: deployment.v1alpha1.DriverGetDeploymentStatusResponse
	(*DriverDeleteDeploymentResponse)(nil),    // 12: deployment.v1alpha1.DriverDeleteDeploymentResponse
	nil,                                       // 13: deployment.v1alpha1.CredentialDetails.SecretsEntry
	nil,                                       // 14: deployment.v1alpha1.DriverCreateDeploymentRequest.ParametersEntry
	(*descriptorpb.EnumOptions)(nil),          // 15: google.protobuf.EnumOptions
	(*descriptorpb.EnumValueOptions)(nil),     // 16: google.protobuf.EnumValueOptions
	(*descriptorpb.FieldOptions)(nil),         // 17: google.protobuf.FieldOptions
	(*descriptorpb.MessageOptions)(nil),       // 18: google.protobuf.MessageOptions
	(*descriptorpb.MethodOptions)(nil),        // 19: google.protobuf.MethodOptions
	(*descriptorpb.ServiceOptions)(nil),       // 20: google.protobuf.ServiceOptions
}
var file_proto_deployment_proto_depIdxs = []int32{
	13, // 0: deployment.v1alpha1.CredentialDetails.secrets:type_name -> deployment.v1alpha1.CredentialDetails.SecretsEntry
	14, // 1: deployment.v1alpha1.DriverCreateDeploymentRequest.parameters:type_name -> deployment.v1alpha1.DriverCreateDeploymentRequest.ParametersEntry
	3,  // 2: deployment.v1alpha1.DriverGetDeploymentStatusResponse.deployment_status:type_name -> deployment.v1alpha1.DeploymentStatusEnum
	15, // 3: deployment.v1alpha1.alpha_enum:extendee -> google.protobuf.EnumOptions
	16, // 4: deployment.v1alpha1.alpha_enum_value:extendee -> google.protobuf.EnumValueOptions
	17, // 5: deployment.v1alpha1.deployment_secret:extendee -> google.protobuf.FieldOptions
	17, // 6: deployment.v1alpha1.alpha_field:extendee -> google.protobuf.FieldOptions
	18, // 7: deployment.v1alpha1.alpha_message:extendee -> google.protobuf.MessageOptions
	19, // 8: deployment.v1alpha1.alpha_method:extendee -> google.protobuf.MethodOptions
	20, // 9: deployment.v1alpha1.alpha_service:extendee -> google.protobuf.ServiceOptions
	5,  // 10: deployment.v1alpha1.Identity.DriverGetInfo:input_type -> deployment.v1alpha1.DriverGetInfoRequest
	7,  // 11: deployment.v1alpha1.Provisioner.DriverCreateDeployment:input_type -> deployment.v1alpha1.DriverCreateDeploymentRequest
	9,  // 12: deployment.v1alpha1.Provisioner.DriverDeleteDeployment:input_type -> deployment.v1alpha1.DriverDeleteDeploymentRequest
	10, // 13: deployment.v1alpha1.Provisioner.DriverGetDeploymentStatus:input_type -> deployment.v1alpha1.DriverGetDeploymentStatusRequest
	6,  // 14: deployment.v1alpha1.Identity.DriverGetInfo:output_type -> deployment.v1alpha1.DriverGetInfoResponse
	8,  // 15: deployment.v1alpha1.Provisioner.DriverCreateDeployment:output_type -> deployment.v1alpha1.DriverCreateDeploymentResponse
	12, // 16: deployment.v1alpha1.Provisioner.DriverDeleteDeployment:output_type -> deployment.v1alpha1.DriverDeleteDeploymentResponse
	11, // 17: deployment.v1alpha1.Provisioner.DriverGetDeploymentStatus:output_type -> deployment.v1alpha1.DriverGetDeploymentStatusResponse
	14, // [14:18] is the sub-list for method output_type
	10, // [10:14] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	3,  // [3:10] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_proto_deployment_proto_init() }
func file_proto_deployment_proto_init() {
	if File_proto_deployment_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_deployment_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeploymentStatusEnum); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_deployment_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CredentialDetails); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_deployment_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DriverGetInfoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_deployment_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DriverGetInfoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_deployment_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DriverCreateDeploymentRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_deployment_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DriverCreateDeploymentResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_deployment_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DriverDeleteDeploymentRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_deployment_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DriverGetDeploymentStatusRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_deployment_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DriverGetDeploymentStatusResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_deployment_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DriverDeleteDeploymentResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_proto_deployment_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*DeploymentStatusEnum_Ready)(nil),
		(*DeploymentStatusEnum_Pending)(nil),
		(*DeploymentStatusEnum_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_deployment_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   12,
			NumExtensions: 7,
			NumServices:   2,
		},
		GoTypes:           file_proto_deployment_proto_goTypes,
		DependencyIndexes: file_proto_deployment_proto_depIdxs,
		EnumInfos:         file_proto_deployment_proto_enumTypes,
		MessageInfos:      file_proto_deployment_proto_msgTypes,
		ExtensionInfos:    file_proto_deployment_proto_extTypes,
	}.Build()
	File_proto_deployment_proto = out.File
	file_proto_deployment_proto_rawDesc = nil
	file_proto_deployment_proto_goTypes = nil
	file_proto_deployment_proto_depIdxs = nil
}
