# permissions for end users to edit examplekinds.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: examplekind-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: deployment-operator
    app.kubernetes.io/part-of: deployment-operator
    app.kubernetes.io/managed-by: kustomize
  name: examplekind-editor-role
rules:
- apiGroups:
  - exampleapi.plural.sh
  resources:
  - examplekinds
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - exampleapi.plural.sh
  resources:
  - examplekinds/status
  verbs:
  - get
