# permissions for end users to view pipelinegates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: pipelinegate-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: deployment-operator
    app.kubernetes.io/part-of: deployment-operator
    app.kubernetes.io/managed-by: kustomize
  name: pipelinegate-viewer-role
rules:
- apiGroups:
  - pipelines.plural.sh
  resources:
  - pipelinegates
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - pipelines.plural.sh
  resources:
  - pipelinegates/status
  verbs:
  - get
