---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - deployments.plural.sh
  resources:
  - customhealths
  - kubecostextractors
  - pipelinegates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - deployments.plural.sh
  resources:
  - customhealths/finalizers
  - kubecostextractors/finalizers
  - pipelinegates/finalizers
  verbs:
  - update
- apiGroups:
  - deployments.plural.sh
  resources:
  - customhealths/status
  - kubecostextractors/status
  - pipelinegates/status
  verbs:
  - get
  - patch
  - update
