---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - deployments.plural.sh
  resources:
  - customhealths
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - deployments.plural.sh
  resources:
  - customhealths/finalizers
  verbs:
  - update
- apiGroups:
  - deployments.plural.sh
  resources:
  - customhealths/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - pipelines.plural.sh
  resources:
  - pipelinegates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - pipelines.plural.sh
  resources:
  - pipelinegates/finalizers
  verbs:
  - update
- apiGroups:
  - pipelines.plural.sh
  resources:
  - pipelinegates/status
  verbs:
  - get
  - patch
  - update
