name: pipeline-demo
stages:
- name: dev
  services:
  - name: mgmt/cd-demo
- name: prod
  services:
  - name: mgmt/cd-demo2
    criteria:
      source: mgmt/cd-demo
      secrets:
      - tag
edges:
- from: dev
  to: prod
  gates:
  - name: example-gate
    type: job
    cluster: mgmt
    clusterId: 15909239-6fac-472d-934f-6c793933cd79
    spec:
      job:
        namespace: default
        containers:
          - image: alpine:3.7
            args:
              - /bin/sh
              - -c
              - echo "Hello, World!"
            env:
              - name: ENV_VAR_1
                value: value1
        serviceAccount: default
