apiVersion: v2
appVersion: v0.6.41
description: creates a new instance of the plural deployment operator
maintainers:
  - name: Plural
    url: https://www.plural.sh
name: deployment-operator
type: application
version: v0.6.41
