name: Refresh Operator Docs
on:
  schedule:
    - cron: '0 0 * * *'
  pull_request: # TODO Remove.
    branches:
      - main
env:
  GOPATH: /home/runner/go/
  GOPROXY: "https://proxy.golang.org"
jobs:
  gendocs:
    runs-on: ubuntu-latest
    permissions:
      contents: 'write'
      id-token: 'write'
      pull-requests: 'write'
    steps:
    - name: 'Checkout'
      uses: actions/checkout@v3
    - name: 'Regenerate Docs'
      run: make crd-docs
      working-directory: ./
    - id: date
      run: echo "date=$(date +%Y-%m-%d)" >> $GITHUB_OUTPUT
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        title: "chore: API documentation sync"
        body: Automated pull request to regenerate API docs for the deployment operator.
        commit-message: Update docs for deployment operator
        branch: docs-${{steps.date.outputs.date}}
        labels: release
        base: main