name: Docs
on:
  schedule:
    - cron: '0 0 * * *'
  pull_request: # TODO Remove.
    branches:
      - main
env:
  GOPATH: /home/runner/go/
  GOPROXY: "https://proxy.golang.org"
jobs:
  docs:
    name: Regenerate
    runs-on: ubuntu-latest
    permissions:
      contents: 'write'
      id-token: 'write'
      pull-requests: 'write'
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Install Go
      uses: actions/setup-go@v4
      with:
        go-version-file: go.mod
        cache: false
    - name: Regenerate docs
      run: pwd && ls -al && make crd-docs
    - name: Save date
      id: date
      run: echo "date=$(date +%Y-%m-%d)" >> $GITHUB_OUTPUT
    - name: Create pull request
      uses: peter-evans/create-pull-request@v5
      with:
        title: "chore: API documentation sync"
        body: Automated pull request to regenerate API docs for the deployment operator.
        commit-message: Update docs for deployment operator
        branch: docs-${{steps.date.outputs.date}}
        labels: release
        base: update-docs # TODO main