name: Publish agent FIPS

on:
  push:
    tags:
      - 'v*.*.*'

env:
  GOPATH: /home/runner/go/
  GOPROXY: "https://proxy.golang.org"

jobs:
  publish-agent-fips:
    name: Build and push agent FIPS container
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
      packages: 'write'
    outputs:
      version: ${{ steps.meta.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/pluralsh/deployment-operator
            docker.io/pluralsh/deployment-operator
          tags: |
            type=semver,pattern={{version}},suffix=-fips,priority=1000
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Login to Docker
        uses: docker/login-action@v3
        with:
          username: mjgpluralsh
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: "."
          file: "./dockerfiles/agent/fips.Dockerfile"
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            GO_FIPS_IMAGE_REPO=ghcr.io/pluralsh/fips/go-fips
            GO_FIPS_IMAGE_TAG=1.25.1

