name: Publish Harness FIPS
on:
  pull_request:
    branches:
    - "main"
  push:
    tags:
    - 'v*.*.*'
env:
  GOPATH: /home/runner/go/
  GOPROXY: "https://proxy.golang.org"
  REGISTRY_IMAGE: pluralsh/stackrun-harness-base

jobs:

  build-base-image:
    name: Build base FIPS image
    permissions:
      contents: 'read'
      id-token: 'write'
      packages: 'write'
    strategy:
      fail-fast: false
      matrix:
        platforms:
          - platform: linux/amd64
            runner: ubuntu-24.04
          - platform: linux/arm64
            runner: ubuntu-24.04-arm
    runs-on: ${{ matrix.platforms.runner }}
    outputs:
      version: ${{ steps.meta.outputs.version }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Prepare
      run: |
        platform=${{ matrix.platforms.platform }}
        echo "PLATFORM_PAIR=${platform//\//-}" >> $GITHUB_ENV
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY_IMAGE }}
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Login to Docker
      uses: docker/login-action@v3
      with:
        username: mjgpluralsh
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
    - name: Build and push by digest
      id: build
      uses: docker/build-push-action@v6
      with:
        context: "."
        file: "./dockerfiles/harness/base.fips.Dockerfile"
        tags: ${{ env.REGISTRY_IMAGE }}
        labels: ${{ steps.meta.outputs.labels }}
        platforms: ${{ matrix.platforms.platform }}
        outputs: type=image,push-by-digest=true,name-canonical=true,push=true
        cache-from: type=gha
        cache-to: type=gha,mode=max
        build-args: |
          VERSION=${{ steps.meta.outputs.version }}
          GO_FIPS_IMAGE_REPO=ghcr.io/pluralsh/go-fips
          GO_FIPS_IMAGE_TAG=1.23.2
    - name: Export digest
      run: |
        mkdir -p ${{ runner.temp }}/digests
        digest="${{ steps.build.outputs.digest }}"
        touch "${{ runner.temp }}/digests/${digest#sha256:}"
    - name: Upload digest
      uses: actions/upload-artifact@v4
      with:
        name: digests-${{ env.PLATFORM_PAIR }}
        path: ${{ runner.temp }}/digests/*
        if-no-files-found: error
        retention-days: 1

  publish-base-image:
    name: Publish base FIPS image
    needs: [ build-base-image ]
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.meta.outputs.version }}
    steps:
      - name: Download digests
        uses: actions/download-artifact@v4
        with:
          path: ${{ runner.temp }}/digests
          pattern: digests-*
          merge-multiple: true
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: mjgpluralsh
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/pluralsh/stackrun-harness-base
            docker.io/pluralsh/stackrun-harness-base
          tags: |
            type=semver,pattern={{version}},suffix=-fips,priority=1000
            type=sha,suffix=-fips,priority=800
            type=ref,event=pr,suffix=-fips,priority=600
      - name: Create manifest list and push
        working-directory: ${{ runner.temp }}/digests
        run: |
          docker buildx imagetools create $(jq -cr '.tags | map("-t " + .) | join(" ")' <<< "$DOCKER_METADATA_OUTPUT_JSON") \
            $(printf '${{ env.REGISTRY_IMAGE }}@sha256:%s ' *)

  publish-harness-ansible:
    name: Build and push harness ansible FIPS container
    runs-on: ubuntu-20.04
    needs: [ publish-base-image ]
    strategy:
      matrix:
        versions:
        - ansible: '7.7.0'
          python: '3.11'
          tag: '7.7'
        - ansible: '8.7.0'
          python: '3.11'
          tag: '8.7'
        - ansible: '9.0.1'
          python: '3.12'
          tag: '9.0'
        - ansible: '10.0.1'
          python: '3.12'
          tag: '10.0'
        - ansible: '11.0.0'
          python: '3.12'
          tag: '11.0'
    permissions:
      contents: write
      discussions: write
      pull-requests: write
      packages: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: |
          ghcr.io/pluralsh/harness
          docker.io/pluralsh/harness
        tags: |
          type=semver,pattern={{version}},suffix=-ansible-${{ matrix.versions.tag }}-fips,priority=1000
          type=sha,suffix=-ansible-${{ matrix.versions.tag }}-fips,priority=800
          type=ref,event=pr,suffix=-ansible-${{ matrix.versions.tag }}-fips,priority=600
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Login to Docker
      uses: docker/login-action@v3
      with:
        username: mjgpluralsh
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: "."
        file: "./dockerfiles/harness/ansible.fips.Dockerfile"
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        platforms: linux/amd64,linux/arm64
        cache-from: type=gha
        cache-to: type=gha,mode=max
        build-args: |
          ANSIBLE_VERSION=${{ matrix.versions.ansible }}
          PYTHON_VERSION=${{ matrix.versions.python }}
          HARNESS_BASE_IMAGE_REPO=ghcr.io/pluralsh/stackrun-harness-base
          HARNESS_BASE_IMAGE_TAG=${{ needs.publish-harness-base.outputs.version }}
          GO_FIPS_IMAGE_REPO=ghcr.io/pluralsh/go-fips
          GO_FIPS_IMAGE_TAG=1.23.2
