name: "Semantic PR"

on:
  workflow_dispatch:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - labeled
      - unlabeled

jobs:
  main:
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  body:
    name: Validate PR body
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.*.labels.*.name, 'dependencies') && !contains(github.event.*.labels.*.name, 'release')}}
    steps:
      - name: Check pull request body for Plural console URL
        run: |
          PR_BODY="${{ github.event.pull_request.body }}"
          
          # Check if body contains the placeholder URL that should be replaced
          if echo "$PR_BODY" | grep -q "https://console.your-env.onplural.sh"; then
            echo "❌ Error: PR body contains placeholder URL 'https://console.your-env.onplural.sh'"
            echo "Replace it with link to a test environment where you have deployed and tested the agent"
            exit 1
          fi
                    
          # Check if body contains a valid link to a test environment
          if echo "$PR_BODY" | grep -E "https://console\.[^.]+\.onplural\.sh" > /dev/null; then
            echo "✅ Valid link to a test environment found in PR body"
            exit 0
          else
            echo "❌ Error: PR body must contain a valid link to a test environment matching pattern 'https://console.*.onplural.sh'"
            echo "Example: https://console.my-env.onplural.sh"
            exit 1
          fi
